@host = https://localhost
@port = 7005
@token = CfDJ8AHCTjzdeFVOpyQbYbe9sOIRToAqGGIv6r7R30qDQr77x_z1gxjcAdtiDjSbY0iovEH9b2cS2LpnBppfGXFDF17gF5Y8cnrkD7LWXkLhpHyjpWG9Lp_blmeK5TeljAWnfYGO_Ik7lxWf-v2W-APC4FXwsbANBWO2jgclXdQ224n0aQ5_SWmv-PFMLEYKa_PeMmB16qHEhgpnANm7jU4XUg4-IGcV9MDL3Ah9jQmDRugOuzHXmzpy3QDmy8sXjR1zjZ6QJK4HsTlyh44TeFbSTRwWpOEZYsSNrCY8JtFxiJJkNM1kTnOf4jleOZSO0HVIzn06_YMsthb25D83h4Eo9tG9DBHDGk1TpLOrR1iVSny2uNXnfOfr19sFOyNJFxeBHHpsJlARpwo06O9qtUjlbZ5xxi8JJR-h7OwcsmO7i6qhgJfoOGks81rdWyLBKBIX2sZdJL708NyQTYSI2OL7T49DLP1_r1ycxk4ob-2GpeWTamq0CTWnP8jAQeFPcJCXVXYi3dAYfpBQtUO2rjm4HX5xfYYVrsYnDMcudVk0Ur5TW49J0JaRW0xinYCIiZ9ShBOJ8kVTwka5E7u-26haW3ubHzfM0T-HE-DGDHsxy7NzjzXpBiY79_WWr9rap3GjaO2TjKx3m16ZnuTwgdmDBWWnSZAqH_4W-_ScZwKYP_mUSU2TwDtGb4wGYV91jQ-4SaugOLXIqod046Ejqgz04DVOWrvtqLsT0D140EAYqbFEdAIvwY858urIu4WAXfyhJ_5McjKomJmJdP5CkZRf2guiQWMMYfz5SNl9iQMOgiU2

@Restaurants.API_HostAddress = https://localhost:7005


GET {{Restaurants.API_HostAddress}}/api/restaurants


###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3
Authorization: Bearer {{token}}

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes

###

GET {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes/3


###

DELETE {{Restaurants.API_HostAddress}}/api/restaurants/1006


###

POST {{Restaurants.API_HostAddress}}/api/restaurants
Authorization: Bearer {{token}}
Content-Type: application/json

{
      "Name": "Tasty Tests3",
      "Description": "A cozy restaurant serving a variety of delicious dishes.",
      "Category": "Indian",
      "HasDelivery": true,
      "ContactEmail": "info@test.com",
      "ContactNumber": "555-1234",
      "City": "New York",
      "Street": "123 Main Street",
      "PostalCode": "10-010"
}

###

GET https://localhost:7005/api/restaurants/1007


###


PATCH {{Restaurants.API_HostAddress}}/api/restaurants/1010
Content-Type: application/json

{
  "Name": "Sample patch2",
  "Description": "This is a sample restaurant description.",
  "HasDelivery": false
}

###

POST {{Restaurants.API_HostAddress}}/api/restaurants/3/dishes
Content-Type: application/json

{
  "Name": "Spaghetti Bolognese",
  "Description": "Classic Italian pasta dish with rich meat sauce",
  "Price": 12.99,
  "KiloCalories": 750
}

###

GET https://localhost:7005/api/restaurants/3/dishes/7



###

POST {{Restaurants.API_HostAddress}}/api/identity/register
Content-Type: application/json

{
    "email": "user@test.com",
    "password": "Password1!"
}

###

POST {{Restaurants.API_HostAddress}}/api/identity/login
Content-Type: application/json

{
    "email": "owner@test.com",
    "password": "Password1!"
}