@host = https://localhost
@port = 7005

@Restaurants.API_HostAddress = {{host}}:{{port}}

GET {{Restaurants.API_HostAddress}}/api/weatherforecast/23/currentDay?max=11
Accept: application/json
ProjectUrl: {{$projectUrl}}
Guid: {{$guid}}
LocalDate: {{$datetime iso8601}} 
Random-int: {{$randomInt}} 

###

POST {{Restaurants.API_HostAddress}}/api/weatherforecast
Content-Type: application/json

"Jakub"